"use client";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { api } from "@/lib/api/client";
import { sessionStore } from "@/lib/auth/session";
type Field={name:string;label:string;type?:string;options?:string[]};type Config={title:string;action:string;fields:Field[];columns:string[]};
const configs:Record<string,Config>={
 consultations:{title:'Consultations',action:'consultations',fields:[{name:'patientId',label:'Patient ID'},{name:'consultationDate',label:'Consultation date',type:'date'},{name:'doctor',label:'Doctor'},{name:'mainConcern',label:'Main concern'},{name:'consultationNotes',label:'Clinical notes',type:'textarea'},{name:'recommendation',label:'Recommendation',type:'textarea'}],columns:['ConsultationID','PatientID','ConsultationDate','Doctor','MainConcern']},
 assessments:{title:'Assessments',action:'assessments',fields:[{name:'patientId',label:'Patient ID'},{name:'assessmentDate',label:'Assessment date',type:'date'},{name:'doctor',label:'Doctor'},{name:'hairLossPattern',label:'Hair-loss pattern'},{name:'norwoodClassification',label:'Norwood classification'},{name:'frontalGrafts',label:'Frontal estimated grafts',type:'number'},{name:'midScalpGrafts',label:'Mid-scalp estimated grafts',type:'number'},{name:'crownGrafts',label:'Crown estimated grafts',type:'number'},{name:'clinicalNotes',label:'Clinical notes',type:'textarea'}],columns:['AssessmentID','PatientID','AssessmentDate','Doctor','NorwoodClassification','EstimatedGrafts']},
 procedures:{title:'Procedures',action:'procedures',fields:[{name:'patientId',label:'Patient ID'},{name:'procedureDate',label:'Procedure date',type:'date'},{name:'doctor',label:'Doctor'},{name:'procedureType',label:'Procedure type'},{name:'plannedGrafts',label:'Planned grafts',type:'number'},{name:'harvestedGrafts',label:'Harvested grafts',type:'number'},{name:'implantedGrafts',label:'Implanted grafts',type:'number'},{name:'procedureStatus',label:'Status',options:['Planned','Scheduled','In Progress','Completed','Cancelled','Rescheduled']},{name:'procedureNotes',label:'Procedure notes',type:'textarea'}],columns:['ProcedureID','PatientID','ProcedureDate','Doctor','ProcedureStatus','ImplantedGrafts']},
 followups:{title:'Follow-ups',action:'followups',fields:[{name:'patientId',label:'Patient ID'},{name:'followUpDate',label:'Follow-up date',type:'date'},{name:'followUpType',label:'Type',options:['Day 1','Week 1','Month 1','Month 3','Month 6','Year 1','Other']},{name:'assignedTo',label:'Assigned to'},{name:'notes',label:'Notes',type:'textarea'}],columns:['FollowUpID','PatientID','FollowUpDate','FollowUpType','Status','AssignedTo']},
 payments:{title:'Payments',action:'payments',fields:[{name:'patientId',label:'Patient ID'},{name:'paymentDate',label:'Payment date',type:'date'},{name:'amount',label:'Amount (NPR)',type:'number'},{name:'method',label:'Method',options:['Cash','Card','Bank transfer','Mobile payment','Other']},{name:'reference',label:'Reference'},{name:'notes',label:'Notes',type:'textarea'}],columns:['PaymentID','PatientID','PaymentDate','Amount','Method','Reference']}
};
export function RecordWorkspace({ module }: { module: string }){const config=configs[module];const [items,setItems]=useState<Record<string,string>[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const session=sessionStore.get();const load=()=>{if(session&&config)api<{items:Record<string,string>[] }>(config.action+'.list',{},session.token).then(x=>setItems(x.items)).catch(e=>setError(e.message));};useEffect(load,[]);if(!config)return null;async function submit(e:FormEvent){e.preventDefault();if(!session)return;setBusy(true);setError('');try{await api(config.action+'.create',form,session.token);setOpen(false);setForm({});load()}catch(e){setError(e instanceof Error?e.message:'Could not save the record.')}finally{setBusy(false)}}return <AppShell title={config.title}><div className="page-title"><div><h2>{config.title}</h2><p className="subtle">Records are stored through the authorized clinic backend.</p></div><button className="button" onClick={()=>setOpen(true)}>Add record</button></div>{error&&<div className="form-error">{error}</div>}<section className="panel"><div className="table-wrap"><table className="table"><thead><tr>{config.columns.map(c=><th key={c}>{c.replace(/([A-Z])/g,' $1')}</th>)}</tr></thead><tbody>{items.length?items.map((r,i)=><tr key={r[config.columns[0]]||i}>{config.columns.map(c=><td key={c}>{r[c]||'—'}</td>)}</tr>):<tr><td className="empty" colSpan={config.columns.length}>No records yet.</td></tr>}</tbody></table></div></section>{open&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><h2>Add {config.title.slice(0,-1)}</h2><div className="grid2">{config.fields.map(f=><label className="field" key={f.name}>{f.label}{f.type==='textarea'?<textarea rows={3} value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})}/>:f.options?<select required value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})}><option value="">Select</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:<input required={f.name==='patientId'||f.name.includes('Date')||f.name==='amount'} type={f.type||'text'} value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})}/>}</label>)}</div><div className="actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button" disabled={busy}>{busy?'Saving…':'Save record'}</button></div></form></div>}</AppShell>}
