function spreadsheet_() { var id=PropertiesService.getScriptProperties().getProperty('NSC_SPREADSHEET_ID'); if(!id) throw clientError_('System storage is not configured.','CONFIGURATION_REQUIRED'); return SpreadsheetApp.openById(id); }
function sheet_(name) { var s=spreadsheet_().getSheetByName(name); if(!s) throw clientError_('Missing required storage sheet: '+name,'CONFIGURATION_ERROR'); ensureHeaders_(s,name); return s; }
function ensureHeaders_(s,name) { try { var exp=NSC_CONFIG.sheets[name]; if(!exp) return; if(s.getLastRow()===0) { s.appendRow(exp); return; } var lastCol=s.getLastColumn(); if(lastCol===0) { s.appendRow(exp); return; } var cur=s.getRange(1,1,1,lastCol).getValues()[0].map(function(h){return String(h).trim();}); var mis=exp.filter(function(e){return !cur.some(function(c){return c.toLowerCase()===e.toLowerCase();});}); if(mis.length>0){ if(lastCol+mis.length>s.getMaxColumns()) s.insertColumnsAfter(lastCol,mis.length); mis.forEach(function(m,i){ s.getRange(1,lastCol+1+i).setValue(m); }); } } catch(e){} }
function rows_(name) { var s=sheet_(name), values=s.getDataRange().getValues(); if(values.length<2) return []; var headers=values[0]; return values.slice(1).filter(function(r){return r[0]!=='';}).map(function(r){var o={};headers.forEach(function(h,i){o[h]=r[i] instanceof Date?Utilities.formatDate(r[i],Session.getScriptTimeZone(),'yyyy-MM-dd HH:mm:ss'):r[i];});return o;}); }
function append_(name, record) { var s=sheet_(name), headers=s.getRange(1,1,1,s.getLastColumn()).getValues()[0]; s.appendRow(headers.map(function(h){return record[h]===undefined?'':record[h];})); }
function find_(name,key,value) { return rows_(name).filter(function(r){return String(r[key]).toLowerCase()===String(value).toLowerCase();})[0]||null; }
function nextId_(prefix) { var lock=LockService.getScriptLock(); lock.waitLock(30000); try { var year=new Date().getFullYear(), prop='NSC_SEQ_'+prefix+'_'+year, n=Number(PropertiesService.getScriptProperties().getProperty(prop)||'0')+1; PropertiesService.getScriptProperties().setProperty(prop,String(n)); return prefix+'-'+year+'-'+('000000'+n).slice(-6); } finally { lock.releaseLock(); } }
function audit_(user,patientId,action,entity,entityId,description) { append_('ActivityLogs',{ActivityID:nextId_('ACT'),PatientID:patientId||'',UserID:user.UserID,Action:action,Entity:entity,EntityID:entityId,Description:description,CreatedAt:new Date()}); }
function initialize_(payload) { var lock=LockService.getScriptLock(); lock.waitLock(30000); try { var props=PropertiesService.getScriptProperties(), id=props.getProperty('NSC_SPREADSHEET_ID'), ss=id?SpreadsheetApp.openById(id):SpreadsheetApp.create(payload.spreadsheetName||'NSC Hair Transplant Data'); if(!id) props.setProperty('NSC_SPREADSHEET_ID',ss.getId()); Object.keys(NSC_CONFIG.sheets).forEach(function(name){var s=ss.getSheetByName(name)||ss.insertSheet(name), h=NSC_CONFIG.sheets[name]; if(s.getLastRow()===0) s.appendRow(h);}); ensureRootFolder_(); return ok_({spreadsheetId:ss.getId(),url:ss.getUrl()}); } finally { lock.releaseLock(); } }
function updateRow_(name, key, value, updates) { var s=sheet_(name), values=s.getDataRange().getValues(), headers=values[0]; var keyCol=headers.findIndex(function(h){return String(h).toLowerCase()===String(key).toLowerCase();}); if(keyCol<0) throw clientError_('Column '+key+' not found in '+name); var rowIndex=values.findIndex(function(r,i){return i>0&&String(r[keyCol]).toLowerCase()===String(value).toLowerCase();}); if(rowIndex<1) throw clientError_('Record not found with '+key+'='+value,'NOT_FOUND'); var updatedKeys=Object.keys(updates); headers.forEach(function(h,colIdx){var matchedKey=updatedKeys.find(function(k){return k.toLowerCase()===h.toLowerCase();}); if(matchedKey!==undefined) s.getRange(rowIndex+1,colIdx+1).setValue(updates[matchedKey]);}); var updatedCol=headers.findIndex(function(h){return String(h).toLowerCase()==='updatedat';}); if(updatedCol>=0) s.getRange(rowIndex+1,updatedCol+1).setValue(new Date()); return true; }
function deleteRow_(name, key, value) { var s=sheet_(name), values=s.getDataRange().getValues(), headers=values[0]; var keyCol=headers.findIndex(function(h){return String(h).toLowerCase()===String(key).toLowerCase();}); if(keyCol<0) throw clientError_('Column '+key+' not found in '+name); var rowIndex=values.findIndex(function(r,i){return i>0&&String(r[keyCol]).toLowerCase()===String(value).toLowerCase();}); if(rowIndex<1) throw clientError_('Record not found with '+key+'='+value,'NOT_FOUND'); s.deleteRow(rowIndex+1); return true; }
